### ISSUE TITLE
What is going on on decode_ltc?

### ISSUE THREAD

**Issue by KatkayApps** [kronihias/smpte-#1]
Hi there, 
Thanks for posting an amazing program for the community. I am trying to use it differently from you. In my case instead of having a file with the total content  I am trying to do it live, or in other words, every x milliseconds I receive a chunk of 1024 audio samples, each sample containing an audio level in the time domain. I am trying to adapt that to your code.

I suppose I need to use decode_ltc. 

void decode_ltc(LTCDecoder *d, ltcsnd_sample_t *sound, size_t size, ltc_off_t posinfo) 

here we have 4 parameters that I am not sure if I understand correctly:

LTCDecoder *d
ltcsnd_sample_t *sound
size_t size
ltc_off_t posinfo

can you please explain what are these 4 variables and what values they carry?

thanks

**Comment by kronihias** [comment]
Hi,
I don't really know what you want to achieve, however the function decode_ltc is from libltc, maybe this helps: https://x42.github.io/libltc/ .
I'm closing this issue as it is no bug.
Best, Matthias
